# Generated by Django 5.0.1 on 2024-03-04 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('e_mail', models.CharField(max_length=50, null=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OffreEmploi',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('entreprise_name', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description_entreprise', models.TextField()),
                ('mission', models.TextField()),
                ('require_profil', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploi.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('cv', models.FileField(upload_to='candidatures/')),
                ('lettre_motivation', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('offre_emploi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploi.offreemploi')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploi.utilisateur')),
            ],
        ),
    ]
