# Generated by Django 5.0.1 on 2024-03-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emploi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidature',
            old_name='member',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='offreemploi',
            old_name='member',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='member',
            new_name='user',
        ),
    ]
