# Generated by Django 5.0.1 on 2024-03-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi', '0002_rename_member_candidature_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='e_mail',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='prenom',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
