# Generated by Django 5.0.1 on 2024-03-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emploi', '0003_candidature_e_mail_candidature_prenom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidature',
            name='user',
        ),
        migrations.RemoveField(
            model_name='offreemploi',
            name='user',
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
