# Generated by Django 5.0.1 on 2024-03-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi', '0005_candidature_user_offreemploi_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
