# Generated by Django 5.0.1 on 2024-02-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0002_alter_message_sujet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
    ]
